import { Injectable, signal, Pipe, PipeTransform } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {
  currentLanguage = signal<string>('en');

  // Basic translation dictionary for demonstration and future expansion
  private translations: Record<string, Record<string, string>> = {
    'en': {
      'DASHBOARD': 'Dashboard',
      'FEES': 'Fees',
      'STUDENT': 'Student',
      'ATTENDANCE': 'Attendance',
      'LEAVE': 'Leave',
      'SIGN_OUT': 'Sign Out',
      'PROFILE': 'Profile',
      
      // Sidebar Navigation
      'NAV_DASHBOARD': 'Dashboard Overview',
      'NAV_STUDENT': 'Student',
      'NAV_STUDENT_ADMISSION': 'Student Admission',
      'NAV_STUDENT_LIST': 'Student List',
      'NAV_ASSIGNMENTS': 'Assignments',
      'NAV_FEES': 'Fees',
      'NAV_FEE_COLLECTION': 'Fee Collection',
      'NAV_FEE_STRUCTURE': 'Fee Structure',
      'NAV_ATTENDANCE': 'Attendance',
      'NAV_MARK_ATTENDANCE': 'Mark Attendance',
      'NAV_VIEW_REPORTS': 'View Reports',
      'NAV_TC': 'Transfer Certificate',
      'NAV_LEAVE_MGMT': 'Leave Management',
      'NAV_INQUIRIES': 'Inquiries',
      'NAV_EMPLOYEES': 'Employees',
      'NAV_EMPLOYEE_LIST': 'Employee List',
      'NAV_COMMISSIONS': 'Commissions',
      'NAV_NOTIFICATIONS': 'Notifications',
      'NAV_SEND_NOTIF': 'Send Notification',
      'NAV_ALL_NOTIF': 'All Notifications',
      'NAV_REPORTS': 'Reports',
      'NAV_MENU': 'Menu',

      // Employee Module
      'EMP_MANAGEMENT_TITLE': 'Employee Management',
      'EMP_MANAGEMENT_DESC': 'Manage staff, assign roles, and handle access control.',
      'EMP_SEARCH_PLACEHOLDER': 'Search by name, code, or designation...',
      'EMP_SEARCH_BTN': 'Search',
      'EMP_COL_EMPLOYEE': 'Employee',
      'EMP_COL_CODE': 'Code',
      'EMP_COL_DESIGNATION': 'Designation',
      'EMP_COL_CONTACT': 'Contact',

      // Leave Management
      'LEAVE_APP_TITLE': 'Leave Application',
      'LEAVE_APP_DESC': 'Apply for leave and manage your leave requests',
      'LEAVE_NEW_REQ': 'New Leave Request',
      'LEAVE_SELECT_CHILD': 'Select Child',
      'LEAVE_START_DATE': 'Start Date',
      'LEAVE_END_DATE': 'End Date',
      'LEAVE_REASON': 'Reason for Leave',
      'LEAVE_SUBMIT': 'Submit Request',
      'LEAVE_HISTORY': 'Leave History',
      'LEAVE_NO_REQ': 'No leave requests found',
      'LEAVE_NO_REQ_DESC': "You haven't submitted any leave applications yet. When you do, they will appear here.",

      // Inquiry Management
      'INQUIRY_TITLE': 'Admission Inquiries',
      'INQUIRY_DESC': 'Manage and follow up on prospective student inquiries',
      'INQUIRY_TOTAL': 'Total Inquiries',
      'INQUIRY_NEW': 'New',
      'INQUIRY_INTERESTED': 'Interested',
      'INQUIRY_CONFIRMED': 'Confirmed',
      'INQUIRY_NOT_INTERESTED': 'Not Interested',
      'INQUIRY_SEARCH': 'Search by name, mobile, or ref...',
      'INQUIRY_STATUS': 'Status:',
      'INQUIRY_ALL': 'All Inquiries',
      'INQUIRY_REF_DATE': 'Ref No / Date',
      'INQUIRY_PARENT_DETAILS': 'Parent Details',
      'INQUIRY_MANAGE_FOLLOWUP': 'Manage Follow-up',

      // Transfer Certificate
      'TC_TITLE': 'Transfer Certificate Module',
      'TC_DESC': 'Generate and manage Transfer Certificates for students.',
      'TC_ISSUE_NEW': 'Issue New TC',
      'TC_SELECT_STUDENT': 'Select Student *',
      'TC_CHOOSE_ACTIVE': '-- Choose Active Student --',
      'TC_NO_ACTIVE_STUDENT': 'No active students available.',
      'TC_REASON': 'Reason for Leaving *',
      'TC_REASON_PLACEHOLDER': 'e.g., Parent transferred to another city',
      'TC_PROGRESS': 'Progress',
      'TC_CONDUCT': 'Conduct',
      'TC_EXCELLENT': 'Excellent',
      'TC_GOOD': 'Good',
      'TC_SATISFACTORY': 'Satisfactory',
      'TC_NEEDS_IMPROVEMENT': 'Needs Improvement',
      'TC_GENERATE_BTN': 'Generate Transfer Certificate',
      'TC_PROCESSING': 'Processing...',
      'TC_DIRECTORY': 'Issued Certificates Directory',
      'TC_NUMBER': 'TC Number',
      'TC_ISSUE_DATE': 'Issue Date',
      'TC_PRINT': 'Print TC',
      'TC_NO_RECORDS': 'No records found',
      'TC_NO_ISSUED': 'No transfer certificates have been issued yet.',

      // Communications (Broadcast & Notifications)
      'BROADCAST_TITLE': 'Broadcast Messaging',
      'BROADCAST_DESC': 'Send instant notifications to all registered student parents via SMS or WhatsApp.',
      'BROADCAST_PLATFORM': 'Platform Selection',
      'BROADCAST_FREE_SMS': 'Free SMS',
      'BROADCAST_STD_TEXT': 'Standard text message',
      'BROADCAST_WHATSAPP': 'WhatsApp',
      'BROADCAST_RICH_MEDIA': 'Rich media messaging',
      'BROADCAST_AUDIENCE': 'Target Audience',
      'BROADCAST_ALL_STUDENTS': 'All Students',
      'BROADCAST_SPECIFIC_CLASS': 'Specific Class',
      'BROADCAST_SELECT_CLASS': 'Select Class',
      'BROADCAST_CHOOSE_CLASS': '-- Choose Class --',
      'BROADCAST_MSG_CONTENT': 'Message Content',
      'BROADCAST_MSG_PLACEHOLDER': 'Type your broadcast message here... e.g. Dear Parents, tomorrow is a school holiday.',
      'BROADCAST_NUMBER_NOTE': 'Numbers will be fetched automatically based on the selected target audience.',
      'BROADCAST_SEND_BTN': 'Send Broadcast',
      'BROADCAST_SENDING': 'Sending...',

      'SEND_NOTIF_TITLE': 'Send Notification',
      'SEND_NOTIF_DESC': 'Directly message targeted groups of teachers or parents.',
      'SEND_NOTIF_COMPOSE': '1. Compose Message',
      'SEND_NOTIF_NOTIF_TITLE': 'Notification Title *',
      'SEND_NOTIF_TITLE_PLACEHOLDER': 'e.g., Important Parent Meeting',
      'SEND_NOTIF_MSG_CONTENT': 'Message Content *',
      'SEND_NOTIF_MSG_PLACEHOLDER': 'Write your message here...',
      'SEND_NOTIF_RECIPIENTS': '2. Select Recipients',
      'SEND_NOTIF_TARGET': 'Target Audience',
      'SEND_NOTIF_TEACHERS': 'Teachers',
      'SEND_NOTIF_PARENTS': 'Parents',
      'SEND_NOTIF_SELECT_USERS': 'Select Users',
      'SEND_NOTIF_SELECTED': 'selected',
      'SEND_NOTIF_SELECT_ALL': 'Select All',
      'SEND_NOTIF_CLEAR': 'Clear',
      'SEND_NOTIF_NO_USERS': 'No users found for this role.',
      'SEND_NOTIF_SEND_BTN': 'Send Notification',

      'NOTIF_INBOX_TITLE': 'Notifications',
      'NOTIF_INBOX_DESC': 'Announcements and alerts from the school.',
      'NOTIF_YOUR_ALERTS': 'Your Alerts',
      'NOTIF_MARK_ALL_READ': 'Mark all as read',
      'NOTIF_LOADING': 'Loading notifications...',
      'NOTIF_NO_NOTIFS': 'No notifications yet',
      'NOTIF_NO_NOTIFS_DESC': 'When the school sends you an alert or message, it will appear here.',
      'NOTIF_NEW_BADGE': 'New',

      // Commission Management
      'COMM_TITLE': 'Commission Management',
      'COMM_DESC': 'Manage teacher referral commissions and view reports.',
      'COMM_CONFIG_TAB': 'Commission Configuration',
      'COMM_REPORTS_TAB': 'Commission Reports',
      'COMM_ACTIVE_STRUCT': 'Active Commission Structure',
      'COMM_CURRENT_RULE': 'Current Rule',
      'COMM_ACTIVE_BADGE': 'Active',
      'COMM_RULE_DESC': 'This rule is applied automatically when a referred student pays their fee.',
      'COMM_TYPE': 'Commission Type',
      'COMM_PERCENTAGE': 'Percentage of Paid Amount',
      'COMM_FIXED': 'Fixed Amount per Payment',
      'COMM_VALUE': 'Commission Value',
      'COMM_UPDATE_BTN': 'Update Active Configuration',
      'COMM_FILTER_TEACHER': 'Filter by Teacher',
      'COMM_ALL_TEACHERS': 'All Teachers',
      'COMM_FROM_DATE': 'From Date',
      'COMM_TO_DATE': 'To Date',
      'COMM_FILTER_BTN': 'Filter',
      'COMM_CLEAR_BTN': 'Clear',
      'COMM_LOADING': 'Loading Reports...',
      'COMM_DATE': 'Date',
      'COMM_TEACHER': 'Teacher',
      'COMM_STUDENT_RECEIPT': 'Student / Receipt',
      'COMM_COMMISSION': 'Commission',
      'COMM_STATUS': 'Status',
      'COMM_ACTION': 'Action',
      'COMM_PAID': 'Paid',
      'COMM_PENDING': 'Pending',
      'COMM_MARK_PAID': 'Mark Paid',
      'COMM_NO_RECORDS': 'No commission records found.',

      // Dashboard Metrics
      'DASH_OVERVIEW': 'Overview Dashboard',
      'DASH_OVERVIEW_DESC': 'Welcome back to the SchoolERP Admin Panel.',
      'DASH_WELCOME_PARENT': 'Welcome,',
      'DASH_WELCOME_STUDENT': 'Welcome to SchoolERP',
      'DASH_METRIC_STUDENTS': 'Total Students',
      'DASH_METRIC_REVENUE': 'Monthly Revenue',
      'DASH_METRIC_ATTENDANCE': 'Average Attendance',
      'DASH_METRIC_STAFF': 'Active Staff',
      'DASH_CHART_TITLE': 'Revenue & Attendance Trends',
      'DASH_CHART_REVENUE': 'Revenue',
      'DASH_CHART_ATT': 'Attendance',
      'DASH_RECENT_ACT': 'Recent Activity',
      'DASH_VIEW_ALL_ACT': 'View All Activity',
      
      // Student Module
      'STUDENT_DIRECTORY': 'Student Directory',
      'STUDENT_DIRECTORY_DESC': 'Manage and view all enrolled students.',
      'ADD_NEW_STUDENT': 'Add New Student',
      'SEARCH_STUDENT': 'Search by name or admission no...',
      'FILTER_CLASS': 'Filter by Class',
      'FILTER_SECTION': 'Filter by Section',
      'STUDENT_DETAILS': 'Student Details',
      'CLASS_SECTION': 'Class/Section',
      'CATEGORY': 'Category',
      'PARENT_CONTACT': 'Parent Contact',
      'STATUS': 'Status',
      'ACTIONS': 'Actions',
      
      // Admission Form
      'PERSONAL_DETAILS': 'Personal Details',
      'PARENT_DETAILS': 'Parent/Guardian Details',
      'ACADEMIC_EXTRAS': 'Academic & Extras',

      // Fee Structure Module
      'FEE_STRUCTURE_TITLE': 'Fee Structure Management',
      'FEE_STRUCTURE_DESC': 'Manage class-wise fee breakdowns and academic year configurations.',
      'FEE_UPDATE_STRUCT': 'Update Structure',
      'FEE_CREATE_STRUCT': 'Create New Structure',
      'FEE_CLASS': 'Class',
      'FEE_ACADEMIC_YEAR': 'Academic Year',
      'FEE_TUITION': 'Tuition Fee (₹)',
      'FEE_TRANSPORT': 'Transport Fee (₹)',
      'FEE_LIBRARY': 'Library Fee (₹)',
      'FEE_MISC': 'Miscellaneous Fee (₹)',
      'FEE_TOTAL': 'Total Fee',
      'FEE_CANCEL': 'Cancel',
      'FEE_SAVE': 'Save Structure',
      'FEE_UPDATING': 'Saving...',
      'FEE_ALL_CLASSES': 'All Classes',
      'FEE_ALL_YEARS': 'All Years',
      'FEE_CLASS_YEAR': 'Class & Year',
      'FEE_TUITION_HEAD': 'Tuition',
      'FEE_TRANSPORT_HEAD': 'Transport',
      'FEE_MISC_LIB_HEAD': 'Misc/Lib',
      'FEE_TOTAL_HEAD': 'Total',
      'FEE_NO_RECORDS': 'No fee structures match your search criteria.',

      // Fee Payments Module
      'FEE_PAYMENTS_TITLE': 'Fee Collection & Records',
      'FEE_PAYMENTS_DESC': 'Process new fee payments and view collection history.',
      'FEE_NEW_PAYMENT': 'New Payment',
      'FEE_PAYMENT_RECORDS': 'Payment Records',
      'FEE_SELECT_STUDENT': 'Select Student',
      'FEE_AMOUNT': 'Amount Paying (₹)',
      'FEE_PAYMENT_METHOD': 'Payment Method',
      'FEE_REMARKS': 'Remarks / Ref No.',
      'FEE_PROCESS_PAYMENT': 'Process Payment',
      'FEE_PROCESSING': 'Processing...',
      'FEE_RECEIPT_NO': 'Receipt No',
      'FEE_DATE': 'Date',
      'FEE_STUDENT': 'Student',

      // Attendance Module
      'ATTENDANCE_TITLE': 'Mark Daily Attendance',
      'ATTENDANCE_DESC': 'Record and manage student attendance for the current day.',
      'ATTENDANCE_DATE': 'Attendance Date',
      'ATTENDANCE_MARK_ALL': 'Mark All Present',
      'ATTENDANCE_MARK_NONE': 'Reset All',
      'ATTENDANCE_SAVE': 'Save Attendance',
      'ATTENDANCE_PRESENT': 'Present',
      'ATTENDANCE_ABSENT': 'Absent',
      'ATTENDANCE_LATE': 'Late',
      'ATTENDANCE_HALF_DAY': 'Half Day',
      'ATTENDANCE_NOT_MARKED': 'Not Marked',
      'ATTENDANCE_REPORT_TITLE': 'Attendance Report',
      'ATTENDANCE_REPORT_DESC': 'View date and class-wise attendance statistics and records.',
      'ATTENDANCE_PRINT': 'Print Report',
      'ATTENDANCE_GENERATE': 'Generate Report',
      'ATTENDANCE_TOTAL_STUDENTS': 'Total Students',
      'ATTENDANCE_PERCENTAGE': 'Attendance %',
      'FIRST_NAME': 'First Name',
      'LAST_NAME': 'Last Name',
      'DOB': 'Date of Birth',
      'GENDER': 'Gender',
      'FATHER_NAME': 'Father\'s Name',
      'MOTHER_NAME': 'Mother\'s Name',
      'CONTACT_NUMBER': 'Contact Number',
      'ADDRESS': 'Residential Address',
      'ADMISSION_CLASS': 'Admission Class',
      'SUBMIT': 'Submit'
    },
    'hi': {
      'DASHBOARD': 'डैशबोर्ड',
      'FEES': 'शुल्क',
      'STUDENT': 'छात्र',
      'ATTENDANCE': 'उपस्थिति',
      'LEAVE': 'छुट्टी',
      'SIGN_OUT': 'साइन आउट',
      'PROFILE': 'प्रोफ़ाइल',
      
      // Sidebar Navigation
      'NAV_DASHBOARD': 'डैशबोर्ड अवलोकन',
      'NAV_STUDENT': 'छात्र',
      'NAV_STUDENT_ADMISSION': 'छात्र प्रवेश',
      'NAV_STUDENT_LIST': 'छात्र सूची',
      'NAV_ASSIGNMENTS': 'कार्य',
      'NAV_FEES': 'शुल्क',
      'NAV_FEE_COLLECTION': 'शुल्क संग्रह',
      'NAV_FEE_STRUCTURE': 'शुल्क संरचना',
      'NAV_ATTENDANCE': 'उपस्थिति',
      'NAV_MARK_ATTENDANCE': 'उपस्थिति दर्ज करें',
      'NAV_VIEW_REPORTS': 'रिपोर्ट देखें',
      'NAV_TC': 'स्थानांतरण प्रमाणपत्र (TC)',
      'NAV_LEAVE_MGMT': 'छुट्टी प्रबंधन',
      'NAV_INQUIRIES': 'पूछताछ',
      'NAV_EMPLOYEES': 'कर्मचारी',
      'NAV_EMPLOYEE_LIST': 'कर्मचारी सूची',
      'NAV_COMMISSIONS': 'कमीशन',
      'NAV_NOTIFICATIONS': 'सूचनाएं',
      'NAV_SEND_NOTIF': 'सूचना भेजें',
      'NAV_ALL_NOTIF': 'सभी सूचनाएं',
      'NAV_REPORTS': 'रिपोर्ट',
      'NAV_MENU': 'मेन्यू',

      // Employee Module
      'EMP_MANAGEMENT_TITLE': 'कर्मचारी प्रबंधन',
      'EMP_MANAGEMENT_DESC': 'कर्मचारियों का प्रबंधन करें, भूमिकाएँ सौंपें, और पहुँच नियंत्रण संभालें।',
      'EMP_SEARCH_PLACEHOLDER': 'नाम, कोड या पदनाम से खोजें...',
      'EMP_SEARCH_BTN': 'खोजें',
      'EMP_COL_EMPLOYEE': 'कर्मचारी',
      'EMP_COL_CODE': 'कोड',
      'EMP_COL_DESIGNATION': 'पदनाम',
      'EMP_COL_CONTACT': 'संपर्क',

      // Leave Management
      'LEAVE_APP_TITLE': 'छुट्टी का आवेदन',
      'LEAVE_APP_DESC': 'छुट्टी के लिए आवेदन करें और अपने अनुरोध प्रबंधित करें',
      'LEAVE_NEW_REQ': 'नया छुट्टी अनुरोध',
      'LEAVE_SELECT_CHILD': 'बच्चा चुनें',
      'LEAVE_START_DATE': 'आरंभ तिथि',
      'LEAVE_END_DATE': 'समाप्ति तिथि',
      'LEAVE_REASON': 'छुट्टी का कारण',
      'LEAVE_SUBMIT': 'अनुरोध जमा करें',
      'LEAVE_HISTORY': 'छुट्टी का इतिहास',
      'LEAVE_NO_REQ': 'कोई छुट्टी अनुरोध नहीं मिला',
      'LEAVE_NO_REQ_DESC': "आपने अभी तक कोई छुट्टी आवेदन जमा नहीं किया है। जब आप करेंगे, तो वे यहां दिखाई देंगे।",

      // Inquiry Management
      'INQUIRY_TITLE': 'प्रवेश पूछताछ',
      'INQUIRY_DESC': 'संभावित छात्र पूछताछ का प्रबंधन और अनुवर्ती कार्रवाई करें',
      'INQUIRY_TOTAL': 'कुल पूछताछ',
      'INQUIRY_NEW': 'नया',
      'INQUIRY_INTERESTED': 'इच्छुक',
      'INQUIRY_CONFIRMED': 'पुष्टि हो गई',
      'INQUIRY_NOT_INTERESTED': 'इच्छुक नहीं',
      'INQUIRY_SEARCH': 'नाम, मोबाइल या संदर्भ से खोजें...',
      'INQUIRY_STATUS': 'स्थिति:',
      'INQUIRY_ALL': 'सभी पूछताछ',
      'INQUIRY_REF_DATE': 'संदर्भ संख्या / तिथि',
      'INQUIRY_PARENT_DETAILS': 'अभिभावक विवरण',
      'INQUIRY_MANAGE_FOLLOWUP': 'अनुवर्ती कार्रवाई प्रबंधित करें',

      // Transfer Certificate
      'TC_TITLE': 'स्थानांतरण प्रमाण पत्र (TC)',
      'TC_DESC': 'छात्रों के लिए टीसी जेनरेट और प्रबंधित करें।',
      'TC_ISSUE_NEW': 'नया टीसी जारी करें',
      'TC_SELECT_STUDENT': 'छात्र चुनें *',
      'TC_CHOOSE_ACTIVE': '-- सक्रिय छात्र चुनें --',
      'TC_NO_ACTIVE_STUDENT': 'कोई सक्रिय छात्र उपलब्ध नहीं है।',
      'TC_REASON': 'छोड़ने का कारण *',
      'TC_REASON_PLACEHOLDER': 'उदा., माता-पिता का दूसरे शहर में स्थानांतरण',
      'TC_PROGRESS': 'प्रगति',
      'TC_CONDUCT': 'आचरण',
      'TC_EXCELLENT': 'उत्कृष्ट',
      'TC_GOOD': 'अच्छा',
      'TC_SATISFACTORY': 'संतोषजनक',
      'TC_NEEDS_IMPROVEMENT': 'सुधार की आवश्यकता',
      'TC_GENERATE_BTN': 'टीसी जेनरेट करें',
      'TC_PROCESSING': 'प्रोसेसिंग...',
      'TC_DIRECTORY': 'जारी किए गए प्रमाण पत्र निर्देशिका',
      'TC_NUMBER': 'टीसी नंबर',
      'TC_ISSUE_DATE': 'जारी करने की तिथि',
      'TC_PRINT': 'टीसी प्रिंट करें',
      'TC_NO_RECORDS': 'कोई रिकॉर्ड नहीं मिला',
      'TC_NO_ISSUED': 'अभी तक कोई स्थानांतरण प्रमाण पत्र जारी नहीं किया गया है।',

      // Communications (Broadcast & Notifications)
      'BROADCAST_TITLE': 'ब्रॉडकास्ट मैसेजिंग',
      'BROADCAST_DESC': 'पंजीकृत छात्रों के माता-पिता को एसएमएस या व्हाट्सएप के माध्यम से त्वरित सूचनाएं भेजें।',
      'BROADCAST_PLATFORM': 'प्लेटफ़ॉर्म चयन',
      'BROADCAST_FREE_SMS': 'मुफ़्त एसएमएस',
      'BROADCAST_STD_TEXT': 'मानक पाठ संदेश',
      'BROADCAST_WHATSAPP': 'व्हाट्सएप',
      'BROADCAST_RICH_MEDIA': 'रिच मीडिया संदेश',
      'BROADCAST_AUDIENCE': 'लक्षित दर्शक',
      'BROADCAST_ALL_STUDENTS': 'सभी छात्र',
      'BROADCAST_SPECIFIC_CLASS': 'विशिष्ट कक्षा',
      'BROADCAST_SELECT_CLASS': 'कक्षा चुनें',
      'BROADCAST_CHOOSE_CLASS': '-- कक्षा चुनें --',
      'BROADCAST_MSG_CONTENT': 'संदेश सामग्री',
      'BROADCAST_MSG_PLACEHOLDER': 'अपना प्रसारण संदेश यहां टाइप करें... उदा. प्रिय माता-पिता, कल स्कूल की छुट्टी है।',
      'BROADCAST_NUMBER_NOTE': 'चयनित दर्शकों के आधार पर संख्या स्वचालित रूप से प्राप्त की जाएगी।',
      'BROADCAST_SEND_BTN': 'प्रसारण भेजें',
      'BROADCAST_SENDING': 'भेज रहा है...',

      'SEND_NOTIF_TITLE': 'अधिसूचना भेजें',
      'SEND_NOTIF_DESC': 'शिक्षकों या माता-पिता के लक्षित समूहों को सीधे संदेश भेजें।',
      'SEND_NOTIF_COMPOSE': '1. संदेश लिखें',
      'SEND_NOTIF_NOTIF_TITLE': 'अधिसूचना का शीर्षक *',
      'SEND_NOTIF_TITLE_PLACEHOLDER': 'उदा., महत्वपूर्ण अभिभावक बैठक',
      'SEND_NOTIF_MSG_CONTENT': 'संदेश सामग्री *',
      'SEND_NOTIF_MSG_PLACEHOLDER': 'अपना संदेश यहाँ लिखें...',
      'SEND_NOTIF_RECIPIENTS': '2. प्राप्तकर्ता चुनें',
      'SEND_NOTIF_TARGET': 'लक्षित दर्शक',
      'SEND_NOTIF_TEACHERS': 'शिक्षक',
      'SEND_NOTIF_PARENTS': 'अभिभावक',
      'SEND_NOTIF_SELECT_USERS': 'उपयोगकर्ताओं का चयन करें',
      'SEND_NOTIF_SELECTED': 'चयनित',
      'SEND_NOTIF_SELECT_ALL': 'सभी चुनें',
      'SEND_NOTIF_CLEAR': 'साफ़ करें',
      'SEND_NOTIF_NO_USERS': 'इस भूमिका के लिए कोई उपयोगकर्ता नहीं मिला।',
      'SEND_NOTIF_SEND_BTN': 'अधिसूचना भेजें',

      'NOTIF_INBOX_TITLE': 'सूचनाएं',
      'NOTIF_INBOX_DESC': 'स्कूल से घोषणाएं और अलर्ट।',
      'NOTIF_YOUR_ALERTS': 'आपके अलर्ट',
      'NOTIF_MARK_ALL_READ': 'सभी को पढ़ा हुआ के रूप में चिह्नित करें',
      'NOTIF_LOADING': 'सूचनाएं लोड हो रही हैं...',
      'NOTIF_NO_NOTIFS': 'अभी तक कोई सूचना नहीं',
      'NOTIF_NO_NOTIFS_DESC': 'जब स्कूल आपको अलर्ट या संदेश भेजेगा, तो वह यहां दिखाई देगा।',
      'NOTIF_NEW_BADGE': 'नया',

      // Commission Management
      'COMM_TITLE': 'कमीशन प्रबंधन',
      'COMM_DESC': 'शिक्षक रेफरल कमीशन का प्रबंधन करें और रिपोर्ट देखें।',
      'COMM_CONFIG_TAB': 'कमीशन कॉन्फ़िगरेशन',
      'COMM_REPORTS_TAB': 'कमीशन रिपोर्ट',
      'COMM_ACTIVE_STRUCT': 'सक्रिय कमीशन संरचना',
      'COMM_CURRENT_RULE': 'वर्तमान नियम',
      'COMM_ACTIVE_BADGE': 'सक्रिय',
      'COMM_RULE_DESC': 'यह नियम स्वचालित रूप से लागू होता है जब कोई संदर्भित छात्र अपनी फीस का भुगतान करता है।',
      'COMM_TYPE': 'कमीशन प्रकार',
      'COMM_PERCENTAGE': 'भुगतान की गई राशि का प्रतिशत',
      'COMM_FIXED': 'प्रति भुगतान निश्चित राशि',
      'COMM_VALUE': 'कमीशन मूल्य',
      'COMM_UPDATE_BTN': 'सक्रिय कॉन्फ़िगरेशन अपडेट करें',
      'COMM_FILTER_TEACHER': 'शिक्षक द्वारा फ़िल्टर करें',
      'COMM_ALL_TEACHERS': 'सभी शिक्षक',
      'COMM_FROM_DATE': 'आरंभ तिथि',
      'COMM_TO_DATE': 'अंतिम तिथि',
      'COMM_FILTER_BTN': 'फ़िल्टर',
      'COMM_CLEAR_BTN': 'साफ़ करें',
      'COMM_LOADING': 'रिपोर्ट लोड हो रही है...',
      'COMM_DATE': 'दिनांक',
      'COMM_TEACHER': 'शिक्षक',
      'COMM_STUDENT_RECEIPT': 'छात्र / रसीद',
      'COMM_COMMISSION': 'कमीशन',
      'COMM_STATUS': 'स्थिति',
      'COMM_ACTION': 'कार्रवाई',
      'COMM_PAID': 'भुगतान किया गया',
      'COMM_PENDING': 'लंबित',
      'COMM_MARK_PAID': 'भुगतान के रूप में चिह्नित करें',
      'COMM_NO_RECORDS': 'कोई कमीशन रिकॉर्ड नहीं मिला।',

      // Dashboard Metrics
      'DASH_OVERVIEW': 'अवलोकन डैशबोर्ड',
      'DASH_OVERVIEW_DESC': 'स्कूल ईआरपी एडमिन पैनल में आपका स्वागत है।',
      'DASH_WELCOME_PARENT': 'स्वागत है,',
      'DASH_WELCOME_STUDENT': 'स्कूल ईआरपी में आपका स्वागत है',
      'DASH_METRIC_STUDENTS': 'कुल छात्र',
      'DASH_METRIC_REVENUE': 'मासिक राजस्व',
      'DASH_METRIC_ATTENDANCE': 'औसत उपस्थिति',
      'DASH_METRIC_STAFF': 'सक्रिय कर्मचारी',
      'DASH_CHART_TITLE': 'राजस्व और उपस्थिति रुझान',
      'DASH_CHART_REVENUE': 'राजस्व',
      'DASH_CHART_ATT': 'उपस्थिति',
      'DASH_RECENT_ACT': 'हाल की गतिविधि',
      'DASH_VIEW_ALL_ACT': 'सभी गतिविधियाँ देखें',
      
      // Student Module
      'STUDENT_DIRECTORY': 'छात्र निर्देशिका',
      'STUDENT_DIRECTORY_DESC': 'सभी नामांकित छात्रों का प्रबंधन और अवलोकन करें।',
      'ADD_NEW_STUDENT': 'नया छात्र जोड़ें',
      'SEARCH_STUDENT': 'नाम या प्रवेश संख्या से खोजें...',
      'FILTER_CLASS': 'कक्षा के अनुसार फ़िल्टर करें',
      'FILTER_SECTION': 'अनुभाग के अनुसार फ़िल्टर करें',
      'STUDENT_DETAILS': 'छात्र का विवरण',
      'CLASS_SECTION': 'कक्षा/अनुभाग',
      'CATEGORY': 'श्रेणी',
      'PARENT_CONTACT': 'अभिभावक संपर्क',
      'STATUS': 'स्थिति',
      'ACTIONS': 'कार्रवाई',

      // Admission Form
      'PERSONAL_DETAILS': 'व्यक्तिगत विवरण',
      'PARENT_DETAILS': 'अभिभावक/संरक्षक विवरण',
      'ACADEMIC_EXTRAS': 'अकादमिक और अन्य विवरण',

      // Fee Structure Module
      'FEE_STRUCTURE_TITLE': 'शुल्क संरचना प्रबंधन',
      'FEE_STRUCTURE_DESC': 'कक्षा-वार शुल्क और शैक्षणिक वर्ष का प्रबंधन करें।',
      'FEE_UPDATE_STRUCT': 'संरचना अपडेट करें',
      'FEE_CREATE_STRUCT': 'नई संरचना बनाएं',
      'FEE_CLASS': 'कक्षा',
      'FEE_ACADEMIC_YEAR': 'शैक्षणिक वर्ष',
      'FEE_TUITION': 'शिक्षण शुल्क (₹)',
      'FEE_TRANSPORT': 'परिवहन शुल्क (₹)',
      'FEE_LIBRARY': 'पुस्तकालय शुल्क (₹)',
      'FEE_MISC': 'विविध शुल्क (₹)',
      'FEE_TOTAL': 'कुल शुल्क',
      'FEE_CANCEL': 'रद्द करें',
      'FEE_SAVE': 'संरचना सहेजें',
      'FEE_UPDATING': 'सहेजा जा रहा है...',
      'FEE_ALL_CLASSES': 'सभी कक्षाएं',
      'FEE_ALL_YEARS': 'सभी वर्ष',
      'FEE_CLASS_YEAR': 'कक्षा और वर्ष',
      'FEE_TUITION_HEAD': 'शिक्षण',
      'FEE_TRANSPORT_HEAD': 'परिवहन',
      'FEE_MISC_LIB_HEAD': 'विविध/पुस्तकालय',
      'FEE_TOTAL_HEAD': 'कुल',
      'FEE_NO_RECORDS': 'आपकी खोज के अनुसार कोई शुल्क संरचना नहीं मिली।',

      // Fee Payments Module
      'FEE_PAYMENTS_TITLE': 'शुल्क संग्रह और रिकॉर्ड',
      'FEE_PAYMENTS_DESC': 'नए शुल्क भुगतान संसाधित करें और संग्रह इतिहास देखें।',
      'FEE_NEW_PAYMENT': 'नया भुगतान',
      'FEE_PAYMENT_RECORDS': 'भुगतान रिकॉर्ड',
      'FEE_SELECT_STUDENT': 'छात्र चुनें',
      'FEE_AMOUNT': 'भुगतान राशि (₹)',
      'FEE_PAYMENT_METHOD': 'भुगतान विधि',
      'FEE_REMARKS': 'टिप्पणी / संदर्भ सं.',
      'FEE_PROCESS_PAYMENT': 'भुगतान संसाधित करें',
      'FEE_PROCESSING': 'प्रसंस्करण...',
      'FEE_RECEIPT_NO': 'रसीद संख्या',
      'FEE_DATE': 'तारीख',
      'FEE_STUDENT': 'छात्र',

      // Attendance Module
      'ATTENDANCE_TITLE': 'दैनिक उपस्थिति दर्ज करें',
      'ATTENDANCE_DESC': 'वर्तमान दिन के लिए छात्र उपस्थिति रिकॉर्ड और प्रबंधित करें।',
      'ATTENDANCE_DATE': 'उपस्थिति तिथि',
      'ATTENDANCE_MARK_ALL': 'सभी उपस्थित चिह्नित करें',
      'ATTENDANCE_MARK_NONE': 'सभी रीसेट करें',
      'ATTENDANCE_SAVE': 'उपस्थिति सहेजें',
      'ATTENDANCE_PRESENT': 'उपस्थित',
      'ATTENDANCE_ABSENT': 'अनुपस्थित',
      'ATTENDANCE_LATE': 'देर से',
      'ATTENDANCE_HALF_DAY': 'आधा दिन',
      'ATTENDANCE_NOT_MARKED': 'चिह्नित नहीं',
      'ATTENDANCE_REPORT_TITLE': 'उपस्थिति रिपोर्ट',
      'ATTENDANCE_REPORT_DESC': 'दिनांक और कक्षा-वार उपस्थिति आंकड़े और रिकॉर्ड देखें।',
      'ATTENDANCE_PRINT': 'रिपोर्ट प्रिंट करें',
      'ATTENDANCE_GENERATE': 'रिपोर्ट तैयार करें',
      'ATTENDANCE_TOTAL_STUDENTS': 'कुल छात्र',
      'ATTENDANCE_PERCENTAGE': 'उपस्थिति %',
      'FIRST_NAME': 'पहला नाम',
      'LAST_NAME': 'अंतिम नाम',
      'DOB': 'जन्म तिथि',
      'GENDER': 'लिंग',
      'FATHER_NAME': 'पिता का नाम',
      'MOTHER_NAME': 'माता का नाम',
      'CONTACT_NUMBER': 'संपर्क नंबर',
      'ADDRESS': 'आवासीय पता',
      'ADMISSION_CLASS': 'प्रवेश कक्षा',
      'SUBMIT': 'जमा करें'
    }
  };

  constructor() {
    this.initLanguage();
  }

  private initLanguage() {
    const savedLang = localStorage.getItem('language');
    if (savedLang === 'hi' || savedLang === 'en') {
      this.currentLanguage.set(savedLang);
    } else {
      this.currentLanguage.set('en');
    }
  }

  setLanguage(lang: string) {
    this.currentLanguage.set(lang);
    localStorage.setItem('language', lang);
  }

  translate(key: string): string {
    const lang = this.currentLanguage();
    return this.translations[lang]?.[key] || key;
  }
}

// A simple pipe to use in HTML templates: {{ 'DASHBOARD' | translate }}
@Pipe({
  name: 'translate',
  standalone: true,
  pure: false // Impure so it updates when language changes
})
export class TranslatePipe implements PipeTransform {
  constructor(private langService: LanguageService) {}

  transform(value: string): string {
    return this.langService.translate(value);
  }
}
